# Geyser GRPC configuration
grpc_url: "https://grpc.ny.shyft.to"
grpc_x_token: "YOUR_API_KEY"

# Solana configuration
keypair_file: "test-wallet2.json"
destination_wallet: "ADQjSTtqr9m5biGuUW91YTpA3FnG68mPfNycvtAfXavr"
transfer_amount: 1000000  # 0.001 SOL 